### ISSUE TITLE
Angular version

### ISSUE THREAD

**Issue by lalmanzar** [cvn/angular-shims-placeholder#20]
Hi, can this be updated to support angular 1.3+ ? right now the bower file says that only supports 1.2~.

**Comment by cvn** [comment]
Hi @lalmanzar, Please try [Release v0.4.0](https://github.com/cvn/angular-shims-placeholder/releases/tag/v0.4.0). It works with Angular 1.3. I also tested it with 1.4.0-beta.6, and it seemed OK.

This was a real pain to get working. The built-in directives in Angular 1.3 are more asynchronous than they were in 1.2. So, cooperating with them meant making this shim more asynchronous. I got it working reliably in my tests, but there could be edge cases I didn't account for. Let me know if you run into any issues.
