### ISSUE TITLE
Placeholder text getting submitted with form

### ISSUE THREAD

**Issue by anandsumeet** [cvn/angular-shims-placeholder#21]
testing in IE8 (emulation mode)
the placeholder text is getting submitted as input value with the form object.  How can this be avoided?

**Comment by cvn** [comment]
If your inputs use ngModel, you can avoid the problem by working with the model values directly. The shim only adds the placeholder text to the DOM, it will not change the model values.

If you're not using ngModel, you can clear the placeholder text on submit. Here's one way to do it with ngSubmit:

```html
<form ng-submit="clearPlaceholders($event)">...</form>
```

```javascript
$scope.clearPlaceholders = function(event){
  // select elements displaying placeholder
  var inputs = event.target.querySelectorAll('.empty');
  // clear elements
  for (var i = 0; i < inputs.length; i++) {
    inputs[i].value = '';
  }
}
```

Demo: http://codepen.io/cvn/pen/waKKXb

It might be possible to add this functionality to the shim, so the elements would clear themselves on submit, and you wouldn't have to handle it manually, but I can't think of a good way to do it yet.

**Comment by anandsumeet** [comment]
Thanks.

**Comment by anandsumeet** [comment]
In my setup, the input and textarea are not showing any empty class

**Comment by cvn** [comment]
If you post your code to a site like codepen, I can take a look. It sounds like it's not configured correctly.

**Comment by anandsumeet** [comment]
difficult. it is a very large application. I'll try a plain setup if it occurs there as well, I'll share the codepen/plunker

**Comment by anandsumeet** [comment]
Sorry...My bad, its there.  when i was inspecting the control had focus so class was not showing.  thanks
