### ISSUE TITLE
DI support

### ISSUE THREAD

**Issue by gilsmdt** [cvn/angular-shims-placeholder#24]
Hi,

Can you please update the code to be DI compatible?
You need to prefix the directive definition like so
.directive('placeholder',['$timeout', '$document', '$interpolate', '$injector', 'placeholderSniffer', function($timeout, $document, $interpolate, $injector, placeholderSniffer) {

don't foget to add the ] at the end of the function :)

**Comment by cvn** [comment]
Check the dist folder.

**Comment by cvn** [comment]
Here's a little more detail, for the people of the future. The source (`lib/`) uses the "implicit annotation" style, and then during the build process, ngmin transforms this into the minification-safe "inline array annotation" style that you've requested, and saves the result in the `dist/` folder.
