### ISSUE TITLE
Tabbing to Password field does not work

### ISSUE THREAD

**Issue by angelaharalson** [cvn/angular-shims-placeholder#28]
Since the text field you are creating in order to show the placeholder for password type fields does not have a tabIndex, it falls to the bottom of the tabbing order. To get it to work in my app, I changed the function to get the tabIndex of the password input and set the tabIndex of the new text input to the same value:
function setupPasswordPlaceholder() {
				var tabIndex = domElem.tabIndex;
				clone = angular.element('\<input tabindex="'+tabIndex+'" type="text" value="'+text+'"/>');
...

**Comment by cvn** [comment]
I can confirm this bug. Thanks for reporting it!

I just pushed a fix for it. Download the latest release and try it out.
