### ISSUE TITLE
No whitespace between some words

### ISSUE THREAD

**Issue by artbelov** [cvn/angular-shims-placeholder#29]
Hello!

On the latest IE9 (v9.0.40) some inputs has no whitespace between words.
![No whitespace](http://i.imgur.com/kJT8Dvc.png)
*Some lost whitespaces are showed by red points.*

Thank you.

---

*I will try to debug this situation later, but, maybe, you have a fast solution for this.*

**Comment by cvn** [comment]
Hi @artbelov. I've never seen this issue before. I just did a few quick tests with my local environment and saw no issues with whitespace. If you are able to make a codepen/jsfiddle/etc demo, we might be able to help more. Let us know if you find out more.

**Comment by artbelov** [comment]
@cvn ok, I will do it soon.

**Comment by artbelov** [comment]
Hello @cvn!
This bug was caused by a conflict with the [jquery.inputmask](https://github.com/RobinHerbots/jquery.inputmask) library.
Thank you for the great work (*this plugin*) :+1:
