### ISSUE TITLE
Can't install

### ISSUE THREAD

**Issue by eranimo** [cvn/angular-shims-placeholder#30]
```
npm ERR! Darwin 14.4.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "angular-shims-placeholder" "--save"
npm ERR! node v0.12.7
npm ERR! npm  v2.11.3
npm ERR! code ELIFECYCLE

npm ERR! angular-shims-placeholder@0.4.5 postinstall: `bower install`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the angular-shims-placeholder@0.4.5 postinstall script 'bower install'.
npm ERR! This is most likely a problem with the angular-shims-placeholder package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     bower install
npm ERR! You can get their info via:
npm ERR!     npm owner ls angular-shims-placeholder
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/kaelan/work/apps/hn-enterprise-portal/npm-debug.log
```

**Comment by cvn** [comment]
angular-shims-placeholder includes bower as an npm dependency and then runs `bower install` as a postinstall script to download some dependencies it needs for running unit tests. This seems to be what's failing, but I don't know why. If you'd like to post your npm-debug.log I can take a look.

You can remove this line in package.json if you just need to get it working quickly:
`    "postinstall": "node_modules/.bin/bower install",`

**Comment by mkoryak** [comment]
doing a bower install during an npm install is just wrong.

**Comment by cvn** [comment]
I removed bower from the npm postinstall, so this error won't happen anymore. Available in the latest release.

**Comment by eranimo** [comment]
Thank you!
