### ISSUE TITLE
Update placeholder after change

### ISSUE THREAD

**Issue by stschaefer** [cvn/angular-shims-placeholder#31]
Hi,

thanks for your directive. :)

I'm changing the placeholder of an input text in my code in this way: $('#inputWithPlaceholder').attr('placeholder', 'new placeholder text');

Unfortunately the new placeholder is not shown in IE. I thought I could force the change by doing something like this:
$('#inputWithPlaceholder').triggerHandler('change');

Am I on the wrong track? Do you have an idea how to solve this problem?

Thanks!

Cheers,
Stefan

**Comment by cvn** [comment]
Hi Stefan,

What you are doing should work. If you look on the [demo page](http://cvn.github.io/angular-shims-placeholder/), under the "No model, change placeholder manually" section, I'm doing this for the "change" button.

If you post an example of the problem on codepen or one of the other js demo sites, I can take a look.

**Comment by cvn** [comment]
Hi @stschaefer,

Since I haven't heard from you, I'm going to close this issue. If you are still having problems, we can reopen.
