### ISSUE TITLE
Empty class nog being applied

### ISSUE THREAD

**Issue by KoenMorren** [cvn/angular-shims-placeholder#33]
Hi,

I've been trying to implement the placeholder shim, but I can't seem to get the class 'empty' to get applied to the input I'm putting the directive on.

I have made a plunker to help showing this.
http://plnkr.co/edit/qH2o9UHhy7YBZ7qkygdi?p=preview

Any idea what I'm doing wrong?

Thanks!

**Comment by KoenMorren** [comment]
I'm guessing this is because I'm checking in a browser that supports the placeholder attribute.

**Comment by cvn** [comment]
Hi @KoenMorren,

You're right, the empty class will only be applied in browsers without placeholder support. If you want to force apply the shim and the empty class in a modern browser for testing, you can do so like this:
```js
angular.module(['testApp'], ['ng.shims.placeholder'])
.run(function(placeholderSniffer){
	// Force enable polyfill in all browsers for demo
	placeholderSniffer.hasPlaceholder = function () { return false; };
});
```
