### ISSUE TITLE
Update bower angular version to 1.5

### ISSUE THREAD

**Issue by joewolschon** [cvn/angular-shims-placeholder#35]
Angular 1.5 was just recently released. I haven't noticed any issues in IE9 and above (including running the tests).

Would it possible get bower.json updated for angular 1.5?

Thanks!

**Comment by cvn** [comment]
Thanks for the nudge, @joewolschon. I did some testing and made the change. Available in the latest release.

**Comment by joewolschon** [comment]
No problem @cvn, thanks for the timely update!
