### ISSUE TITLE
how to  set  in a custome directive  like in div tag

### ISSUE THREAD

**Issue by weixiangzhe** [cvn/angular-shims-placeholder#37]
I used a directive to replace native select ,and placeholder can't show , how to show it?

**Comment by cvn** [comment]
hey @weixiangzhe, select elements don't support the placeholder attribute. There's ways to get a similar effect though. I did a quick Google search and found this StackOverflow [thread](http://stackoverflow.com/questions/5805059/how-do-i-make-a-placeholder-for-a-select-box). Maybe those techniques will work for you.

**Comment by weixiangzhe** [comment]
IT NICE WORK !! Thx 
now  , I think I should learn more English ...
