### ISSUE TITLE
Update bower to support angular 1.6.

### ISSUE THREAD

**Issue by joewolschon** [cvn/angular-shims-placeholder#38]
This may be a little preemptive, but I was getting a head start updating our app to the 1.6 release candidate and I haven't had any issues yet with this library supporting it. 

Is there a chance we can get the bower file updated to support this?

**Comment by cvn** [comment]
Good idea, @joewolschon. I tested with 1.6.0-rc.2 and there were no issues. I set the dependencies so that all future 1.x releases will be supported. Available in the latest release, 0.4.8.

**Comment by joewolschon** [comment]
Sweet, @cvn I meant to suggest that. 

Thanks so much for the quick update and release!
